<a href="https://colab.research.google.com/github/Kashi-2002/Book_By_Brain/blob/main/DE_features_extracted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***The data used here is the preprocessed seed dataset that was in the form of npz file which contained array corresponding to each person.It was then transformed to a dataframe in which each column specified a paticular feature.***

In [ ]:
import numpy as np
import pickle
import os
import pandas as pd

# check the version of these modules
print(np.__version__)
print(pickle.format_version)

1.20.3
4.0

In [ ]:
os.chdir('D:\EEG to emotion\EEG_DE_features')

In [ ]:
os.listdir()

['10_123.npz',
 '11_123.npz',
 '12_123.npz',
 '13_123.npz',
 '14_123.npz',
 '15_123.npz',
 '16_123.npz',
 '1_123.npz',
 '2_123.npz',
 '3_123.npz',
 '4_123.npz',
 '5_123.npz',
 '6_123.npz',
 '7_123.npz',
 '8_123.npz',
 '9_123.npz']

In [ ]:
final_data=np.zeros((16*1823,310))
final_label=np.zeros((16*1823,1))

In [ ]:
m=0
for i in range(16):
    path=os.listdir()[i]
    data_npz = np.load(path)
    data = pickle.loads(data_npz['data'])
    label = pickle.loads(data_npz['label'])
    for j in range(45):
        for l in range(data[j].shape[0]):
            for k in range(310):
                final_data[m][k]=data[j][l][k]
                final_label[m]=label[j][l]
            
            m=m+1

1823
3646
5469
7292
9115
10938
12761
14584
16407
18230
20053
21876
23699
25522
27345
29168

In [ ]:
df=np.concatenate((final_data,final_label),axis=1)

In [ ]:
col_names=[]
for i in range(310):
    col_names.append('feature'+str(i))
    
col_names.append('label')

In [ ]:
seed_2=pd.DataFrame(df,columns=col_names)
seed_2

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,...,feature301,feature302,feature303,feature304,feature305,feature306,feature307,feature308,feature309,label
0,10.356102,8.453970,9.182864,6.004890,5.141894,10.290716,8.406716,9.207439,5.734522,4.649539,...,7.283657,8.523224,5.003387,2.879170,9.615048,7.721449,8.756285,5.505700,3.557300,4.0
1,10.354815,8.453036,9.182566,6.004623,5.141820,10.289452,8.405880,9.207191,5.734266,4.649478,...,7.283529,8.523248,5.003657,2.879481,9.615013,7.721393,8.756245,5.505755,3.557400,4.0
2,10.352640,8.451730,9.182253,6.004298,5.141673,10.287379,8.404652,9.206818,5.733827,4.649188,...,7.283271,8.523222,5.004054,2.879892,9.614570,7.721243,8.756308,5.505813,3.557577,4.0
3,10.350465,8.450617,9.181642,6.004049,5.141211,10.285401,8.403554,9.206070,5.733409,4.648416,...,7.282900,8.523018,5.004297,2.880240,9.613893,7.721066,8.756528,5.505806,3.557766,4.0
4,10.347972,8.448817,9.180328,6.003959,5.140420,10.283218,8.401791,9.204567,5.733128,4.647245,...,7.282056,8.522784,5.004463,2.880605,9.612883,7.720556,8.756705,5.505800,3.558054,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29163,13.194414,11.056482,8.473696,6.289591,5.224470,13.149945,10.928947,8.334800,6.132802,5.063134,...,8.695868,6.938516,5.447935,4.017493,9.772625,8.791983,6.961640,5.557422,4.219654,0.0
29164,13.197743,11.059145,8.473367,6.288137,5.224715,13.153941,10.931755,8.334083,6.131203,5.063185,...,8.696557,6.937651,5.448157,4.018655,9.771082,8.792811,6.960881,5.557415,4.220917,0.0
29165,13.199857,11.060901,8.472648,6.286732,5.224769,13.156656,10.933649,8.333033,6.129622,5.063147,...,8.697358,6.936938,5.448254,4.019552,9.769717,8.793770,6.960305,5.557380,4.221877,0.0
29166,13.201002,11.062336,8.471964,6.285544,5.224847,13.158314,10.935220,8.332127,6.128232,5.063217,...,8.698238,6.936632,5.448181,4.020114,9.768685,8.794774,6.960106,5.557252,4.222538,0.0
29167,13.202382,11.063902,8.472269,6.285020,5.225030,13.159976,10.936876,8.332343,6.127643,5.063460,...,8.698773,6.936782,5.447984,4.020407,9.768294,8.795413,6.960333,5.557004,4.222898,0.0

In [ ]:
seed_2.to_csv('seed_2.csv')